### PR TITLE
upgrade spandex

### PR DESCRIPTION
**Pull request by D-Town44**
Upgrading spandex dep from 2.0 to 3.0. No breaking changes as of https://github.com/spandex-project/spandex#20-upgrade-guide

### CODE REVIEW

**Comment by thiamsantos** [comment]
Thanks for the PR @D-Town44 . I will try to take a look on it this week :)

**Comment by thiamsantos** [comment]
Thanks @D-Town44

**Comment by thiamsantos** [comment]
Published at https://hex.pm/packages/spandex_tesla/1.0.0

**Comment by D-Town44** [comment]
Awesome! Thanks!

**Pull request merged**
