### PR TITLE
Apologies, I'm an idiot: Get the correct unit this time

### PR DESCRIPTION
**Pull request by aselder**
I’m a complete idiot and messed up in my last PR.

milliseconds was definitely not right, but I had a brain fart and went too far in the other direction.

The correct unit should be microseconds. I apologize for not testing end to end.

### CODE REVIEW

**Comment by thiamsantos** [comment]
@aselder Are you sure about that? https://github.com/spandex-project/spandex_ecto/blob/master/lib/spandex_ecto/ecto_logger.ex#L114 spandex_ecto seems to also use nanoseconds.

**Comment by aselder** [comment]
You right.. I'm being an idiot again... I'll have a fix shortly... There's another bug in there... :)

**Comment by aselder** [comment]
You're listening for the `[:tesla, :request]` event which is there legacy event and that time is given in microseconds. 

https://github.com/teamon/tesla/blob/586c54372cef5ff8bcb570d2c1ad06fa2b81b833/lib/tesla/middleware/telemetry.ex#L112-L120

Datadog expects nanoseconds and System.system_time give `:native` units...

**Comment by aselder** [comment]
I'll get another PR to start listening to the non-legacy events in a bit as well.

**Comment by thiamsantos** [comment]
Thanks @aselder

**Comment by thiamsantos** [comment]
Published https://hex.pm/packages/spandex_tesla/1.1.1

**Pull request merged**
